# -*- coding: utf-8 -*-
# Copyright 2022-Today TechKhedut.
# Part of TechKhedut. See LICENSE file for full copyright and licensing details.
{
    'name': "Sunset",
    'version': "19.0.5.9",
    'description': "A car rental, hire car or car hire agency is a company that rents automobiles for short periods.",
    'summary': "Vehicle Rental Management",
    'author': 'Cositt',
    'website': "https://cositt.com",
    'depends': [
        'mail',
        'contacts',
        'product',
        'fleet',
        'sale_management',
        'maintenance',
        'hr_expense',
        'crm',
        'website',
        'portal',
        'account',           # NUEVO - para account.move
        'payment',           # NUEVO - para payment.transaction
        'payment_redsys',    # NUEVO - para integración Redsys
    ],
    'data': [
        # Data
        'data/vehicle_product_data_views.xml',
        # 'data/vehicle_rental_products_2025.xml',  # Temporalmente deshabilitado - crear productos manualmente
        #         'data/fleet_vehicle_category_data.xml',
        'data/sequence_views.xml',
        'data/vehicle_rental_mail_template.xml',
        'data/report_paper_format.xml',
        'data/ir_cron.xml',
        'data/website_menu.xml',
        'data/vehicle_deposit_rule_access.xml',
        # Security
        'security/ir.model.access.csv',
        'security/security.xml',
        # Wizards
        'wizards/vehicle_damage_views.xml',
        'wizards/rental_contract_booking_views.xml',
        'wizards/maintenance_request_bill_views.xml',
        'wizards/lead_rental_contract_views.xml',
        'wizards/return_deposit_views.xml',
        'wizards/damage_painter_wizard_views.xml',
        'wizards/vehicle_substitution_wizard_views.xml',
        'wizards/substitution_damage_painter_wizard_views.xml',
        'wizards/sale_order_to_vehicle_contract_views.xml',
        # Views
        'views/vehicle_deposit_rule_views.xml',
        'views/assets.xml',
        'views/fleet_inherit_views.xml',
        'views/fleet_vehicle_model_views.xml',
        'views/vehicle_contract_views.xml',
        'views/customer_document_views.xml',
        'views/cancellation_policy_views.xml',
        'views/invoice_inherit_views.xml',
        'views/vehicle_scratch_report_views.xml',
        'views/maintenance_schedule_views.xml',
        'views/maintenance_inherit_views.xml',
        'views/rental_agreement_terms_views.xml',
        'views/hr_expense_views.xml',
        'views/crm_lead_views.xml',
        'views/sale_order_views.xml',
        # Sistema de Tarifas Automático 2025
        'views/vehicle_pricing_rule_views.xml',
        'views/vehicle_insurance_pricing_views.xml',
        'views/vehicle_contract_pricing_views.xml',
        # Reports
        'reports/vehicle_contract_report.xml',
        'report/vehicle_contract_report_views.xml',
        'report/scratch_report_views.xml',
        'report/vehicle_substitution_addendum_report.xml',
        # Email templates (después de reports para que existan los XMLID referenciados)
        'data/email_templates.xml',
        # Views de sustitución (después del reporte)
        'views/vehicle_substitution_views.xml',
        # Web Templates
        'views/templates/web_contract_booking_views.xml',
        'views/templates/booking_enquiry_simple.xml',
        'views/templates/booking_enquiry_minimal.xml',
        'views/templates/booking_enquiry_ultra_simple.xml',
        'views/templates/booking_enquiry_with_images.xml',
        'views/templates/test_vehicle_detail.xml',
        'views/templates/vehicle_detail_simple.xml',
        'views/templates/vehicle_detail_working.xml',
        'views/templates/vehicle_detail_final_working.xml',
        'views/templates/vehicle_detail_final.xml',
        'views/templates/vehicle_detail_with_navbar.xml',
        'views/templates/vehicle_detail_template.xml',
        'views/templates/vehicle_detail_test.xml',
        'views/templates/sunset_home_page.xml',
        'views/templates/sunset_home_simple.xml',
        'views/templates/sunset_home_basic.xml',
        'views/templates/sunset_fleet_page.xml',
        'views/templates/sunset_contact_page.xml',
        'views/templates/sunset_contact_simple.xml',
        'views/templates/sunset_contact_basic.xml',
        'views/templates/sunset_contact_success.xml',
        'views/templates/sunset_services_page.xml',
        # Pinveco Templates
        'views/templates/pinveco_home_basic.xml',
        'views/templates/pinveco_fleet_page.xml',
        # Test Templates
        'views/templates/test_fleet_page.xml',
        'views/templates/simple_fleet_page.xml',
        'views/templates/debug_fleet_page.xml',
        'views/redsys_payment_form.xml',
        'views/redsys_checkout.xml',
        # Menus (debe estar al final para que se carguen DESPUÉS de todas las vistas y actions)
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vehicle_rental/static/src/xml/template.xml',
            'vehicle_rental/static/src/scss/style.scss',
            'vehicle_rental/static/src/js/lib/moment.min.js',
            'vehicle_rental/static/src/js/lib/apexcharts.js',
            'vehicle_rental/static/src/js/lib/xy.js',
            'vehicle_rental/static/src/js/lib/index.js',
            'vehicle_rental/static/src/js/lib/Animated.js',
            'vehicle_rental/static/src/js/lib/dhtmlxgantt.css',
            'vehicle_rental/static/src/js/lib/dhtmlxgantt.js',
            'vehicle_rental/static/src/xml/availability_template.xml',
            'vehicle_rental/static/src/js/availability_template.js',
            'vehicle_rental/static/src/js/dashboard/vehicle_rental_dashboard.js',
            'vehicle_rental/static/src/js/damage_painter.js',
            'vehicle_rental/static/src/xml/floating_notification.xml',
            'vehicle_rental/static/src/js/floating_notification.js',
            'vehicle_rental/static/src/scss/floating_notification.scss',
            'vehicle_rental/static/src/xml/delay_notification.xml',
            'vehicle_rental/static/src/js/delay_notification.js',
            'vehicle_rental/static/src/scss/delay_notification.scss',
        ],
        'web.assets_frontend': [
            'vehicle_rental/static/src/css/fleet_grid.css',
            'vehicle_rental/static/src/js/card_validation.js',
        ],
    },
    'images': ['static/description/cover.gif'],
    'license': 'OPL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 110,
    'currency': 'USD',
}
